### ISSUE TITLE
Cannot find module 'geo-coordinates-parser' or its corresponding type declarations.ts (2307)

### ISSUE THREAD

**Issue by Antoine-lb** [ianengelbrecht/geo-coordinates-parser#16]
Hello 👋
Thanks for this package, really helpful!

I installed the package with yarn:
```shell
yarn add geo-coordinates-parser
```

And because we are on a rather strict project in regards to typescript (https://github.com/OneFolderApp/OneFolder), usually I need to follow each installation with something like:
```shell
yarn add @types/geo-coordinates-parser
```

But for `geo-coordinates-parser` it doesn't work, and I don't know what to do to remove the error.

Besides that the package works great!

Thanks for your time.

**Comment by ianengelbrecht** [comment]
I've just updated the package with a [pull request including type definition files](https://github.com/ianengelbrecht/geo-coordinates-parser/pull/13). Please install latest version and try again, and if still failing reply here.

**Comment by Antoine-lb** [comment]
Award winning reactivity right there.

My new problem: my code sucks and it's filled with typescript errors 😂

I will re-open the issue if I find something. Thanks!
