### ISSUE TITLE
Parsing integers doesn't work anymore

### ISSUE THREAD

**Issue by tobiaswaltl** [ianengelbrecht/geo-coordinates-parser#4]
When parsing integers the lib throws a "degree only coordinate provided" error now.

Probably introduced with this commit: https://github.com/ianengelbrecht/geo-coordinates-parser/commit/62bb4584963dff7d5c41adb19b4db59bc978f5f5

Repro:

```
var geoCoordinatesParser = require("geo-coordinates-parser")

geoCoordinatesParser('46,8')
```

**Comment by ianengelbrecht** [comment]
Hi Tobias, can you provide one or two examples please?

**Comment by ianengelbrecht** [comment]
Thanks @tobiaswaltl, may I ask what the source of these coordinates is? It's not likely that 46,8 is a correctly recorded geographic coordinate pair, but I suppose it depends on the specific application. Please let me know, thank you.

**Comment by ianengelbrecht** [comment]
Issue fixed in 1.5.1

**Comment by tobiaswaltl** [comment]
Thanks for the quick fix!
I agree that having integer geo coordinates is an edge case that is rather unlikely. In my case the source is user input from which I extract the coordinates using `geo-coordinates-parser`.
The issue did not show up in production but in a unit test.

**Comment by ianengelbrecht** [comment]
Okay thanks @tobiaswaltl, glad you got it. Note that the update is now also stricter about each side of the coordinates (the lat and long) being in the same format, which is meant to help catch errors.  I'll close the issue then.

**Comment by ianengelbrecht** [comment]
Hi @tobiaswaltl , just a heads up that latest update is going to throw in your unit test for '46,8' again. I need to be consistent with this, and the README says no integer coordinates allowed. If you think you might encounter this in production please put a regex in front of geoCoordinatesParser to catch it first.

**Comment by tobiaswaltl** [comment]
Ok, thank you for the hint.
